language: python
python:
    - "2.7"
    - "3.5"
sudo: false
install:
    - "pip install -r travis-ci/requirements.txt"
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pip-cache    
before_script:
    - createdb -U postgres open511
    - psql -U postgres -d open511 -c "CREATE EXTENSION postgis"
    - python setup.py develop
    - cd travis-ci
    - python manage.py migrate --noinput
script:
    - python manage.py test django_open511_ui